version: "3"
services:
  nginx:
    image: nginx:1.14.0-alpine-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/etc/conf.d:/etc/nginx/conf.d:ro"
      - "./nginx/html:/usr/share/nginx/html"
    environment:
      TZ: 'Asia/Hong_Kong'
    links:
      - mysql:mysql
      - php:php-fpm
    depends_on:
      - mysql
      - php
  mysql:
    image: mysql:5.7.21
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/etc/my.cnf:/etc/mysql/my.cnf:ro"
      - "./mysql/data:/var/lib/mysql"
    environment:
      TZ: 'Asia/Hong_Kong'
      MYSQL_ROOT_PASSWORD: '123456'
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/data:/var/lib/mongo"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  php:
    build: ./php
    image: "php:7.0-fpm"
    command: php-fpm
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - "./php/etc/php.ini:/usr/local/etc/php/conf.d/php.ini:ro"
      - "./nginx/html:/var/www/html"
    environment:
      TZ: 'Asia/Hong_Kong'
    links:
      - mysql:mysql